language: c
script: bash -ex .travis-ci.sh
env:
  global:
    - OPAM_DEPENDS="async cmdliner core cstruct ounit pa_ounit quickcheck tdk ulex ipaddr yojson"
    - CONFIG_FLAGS="--enable-tests --enable-quickcheck --enable-async"
    - FRENETIC_DEPENDS="ocaml-packet ocaml-openflow ocaml-topology"
  matrix:
    - OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.0
    - OCAML_VERSION=4.01.0 OPAM_VERSION=1.2.0
    - OCAML_VERSION=4.02.0 OPAM_VERSION=1.1.0
    - OCAML_VERSION=4.02.0 OPAM_VERSION=1.2.0
notifications:
  irc:
    channels:
      - "irc.freenode.net#frenetic"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}): %{message}"
      - "Build details : %{build_url}"
    on_success: change
    on_failure: always
